### ISSUE TITLE
Segfault when using `lxd_publish_image` for a `virtual-machine` instance

### ISSUE THREAD

**Issue by Unitiser** [terraform-lxd/terraform-provider-lxd#272]
# Segfault when using `lxd_publish_image` for a `virtual-machine` instance

The `terraform-lxd/lxd` plugin segfaults when we try to publish an image for a `virtual-machine` instance.

When trying to understand the issue, I noticed that :
- The plugin crashes before the build begins
- Publishing regular container work as expected

## Sample configuration

Here is a sample configuration to reproduce the issue :

```
terraform {
  required_providers {
    lxd = {
      source = "terraform-lxd/lxd"
    }
  }
}

provider "lxd" {
  lxd_remote {
    name     = "${var.lxd_provider_name}"
    scheme   = "${var.lxd_provider_scheme}"
    address  = "${var.lxd_provider_address}"
    default  = true
    port     = "${var.lxd_provider_port}"
  }
}

resource "lxd_network" "lab" {
  name = "lab2"

  config = {
    "ipv4.address" = "10.0.2.1/24"
    "ipv4.nat"     = "true"
    "ipv6.address" = "none"
  }
}

resource "lxd_profile" "lab" {
  name = "lab2"

  device {
    name = "eth0"
    type = "nic"

    properties = {
      nictype = "bridged"
      parent  = "${lxd_network.lab.name}"
    }
  }
  
  device {
    name = "root"
    type = "disk"
    
    properties = {
      pool = "btrfs-pool"
      path = "/"
    }
  }
}

resource "lxd_container" "test" {
  name      = "test1"
  image     = "win10"
  type      = "virtual-machine"
  
  ephemeral = false
  profiles  = ["${lxd_profile.lab.name}"]
  
  config = {
    "boot.autostart" = true
    "security.secureboot" = false
    "limits.cpu" = "2"
    "limits.memory" = "4GB" 
  }
}

resource "lxd_publish_image" "test" {
  container = "test1"
  aliases   = [ "test1" ]
}
```

## Stacktrace

```
Stack trace from the terraform-provider-lxd_v1.7.2 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xdb1269]

goroutine 44 [running]:
github.com/terraform-lxd/terraform-provider-lxd/lxd.resourceLxdPublishImageCreate(0xc0002518f0, 0xf8b820, 0xc0001d00c0, 0x2, 0x16e9100)
        github.com/terraform-lxd/terraform-provider-lxd/lxd/resource_lxd_publish_image.go:80 +0x169
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc00045a870, 0xc000172b90, 0xc0005c3720, 0xf8b820, 0xc0001d00c0, 0xe93d01, 0xc0004295f8, 0xc000291590)
        github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/resource.go:310 +0x375
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc00018c100, 0xc000307a18, 0xc000172b90, 0xc0005c3720, 0xc000293288, 0xc00000e908, 0xe96420)
        github.com/hashicorp/terraform-plugin-sdk@v1.15.0/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000e758, 0x1162030, 0xc000290a20, 0xc000251260, 0xc00000e758, 0xc000290a20, 0xc000675b80)
        github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/helper/plugin/grpc_provider.go:885 +0x8a5
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0xf85180, 0xc00000e758, 0x1162030, 0xc000290a20, 0xc00017a9c0, 0x0, 0x1162030, 0xc000290a20, 0xc000378120, 0x106)
        github.com/hashicorp/terraform-plugin-sdk@v1.15.0/internal/tfplugin5/tfplugin5.pb.go:3305 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000438c00, 0x116a538, 0xc000001680, 0xc0005de600, 0xc00009e6c0, 0x16a9320, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1024 +0x522
google.golang.org/grpc.(*Server).handleStream(0xc000438c00, 0x116a538, 0xc000001680, 0xc0005de600, 0x0)
        google.golang.org/grpc@v1.27.1/server.go:1313 +0xd2c
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0005821c0, 0xc000438c00, 0x116a538, 0xc000001680, 0xc0005de600)
        google.golang.org/grpc@v1.27.1/server.go:722 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.27.1/server.go:720 +0xa5

Error: The terraform-provider-lxd_v1.7.2 plugin crashed!
```

## Workaround

We can replace `lxc_publish_image` : 

```
resource "lxd_publish_image" "test" {
  container = "test1"
  aliases   = [ "test1" ]
}
```

With a `null_resource` executing a `local-exec` :

```
resource "null_resource" "manual-publish" {
  provisioner "local-exec" {
    command = "lxc stop ${var.lxd_provider_name}:${lxd_container.test.name} -f"
  }
  
  provisioner "local-exec" {
    command = "lxc publish ${var.lxd_provider_name}:${lxd_container.test.name} ${var.lxd_provider_name}: --alias ${lxd_container.test.name}"
  }
}
```

**Comment by jtopjian** [comment]
@Unitiser #274 might fix this issue. I was able to reproduce the error you saw using containers rather than virtual machines.

I don't have experience using LXD with virtual machines, so I'm not sure if #274 will completely fix the issue you're seeing, but it might. If you know how to compile this provider from source and try it out, that would help with confirmation.

**Comment by Unitiser** [comment]
@jtopjian I tested your fix. The check you added indeed fixes the nil pointer and replace the crash with a container not found error. This time, the build starts and the container is created. We still end up with the container not found error. 

The function `GetContainerState` from the LXD module does not seem to return the expected result. As I am not too familiar with golang I will try to reproduce the issue with pylxd to investigate further.

**Comment by jtopjian** [comment]
@Unitiser Nice - glad to hear. I will create a new release with this fix now.

I think that this point, it might just be an ordering issue with your Terraform manifest. 

With the following in mind:

```hcl
resource "lxd_container" "test" {
  name      = "test1"
  image     = "win10"
  type      = "virtual-machine"
  
  ephemeral = false
  profiles  = ["${lxd_profile.lab.name}"]
  
  config = {
    "boot.autostart" = true
    "security.secureboot" = false
    "limits.cpu" = "2"
    "limits.memory" = "4GB" 
  }
}

resource "lxd_publish_image" "test" {
  container = "test1"
  aliases   = [ "test1" ]
}
```

Terraform does not execute in a top-down fashion. It executes in parallel, unless there are implicit or explicit dependencies between resources.

An example of an implicit dependency is:

```hcl
resource "lxd_container" "test" {
  name      = "test1"
  image     = "win10"
  type      = "virtual-machine"
  
  ephemeral = false
  profiles  = ["${lxd_profile.lab.name}"]
  
  config = {
    "boot.autostart" = true
    "security.secureboot" = false
    "limits.cpu" = "2"
    "limits.memory" = "4GB" 
  }
}

resource "lxd_publish_image" "test" {
  container = "${lxd_container.test.name}"
  aliases   = [ "test1" ]
}
```

Maybe that will help?

**Comment by jtopjian** [comment]
Good point. If someone wanted to implement that change, I'm happy to review/merge it. Unfortunately I only have enough capacity to fix crashes at the moment.
