### ISSUE TITLE
Panic during cached image migration on v2.0.0

### ISSUE THREAD

**Issue by matifali** [terraform-lxd/terraform-provider-lxd#420]
While trying to update the lxd provider, it panics if no lxd daemon is running.

```console
Plan: 1 to add, 0 to change, 1 to destroy.
Error: Plugin did not respond
The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
Error: Plugin did not respond
The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
Error: Plugin did not respond
The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
Stack trace from the terraform-provider-lxd_v2.0.0 plugin:
panic: runtime error: index out of range [1] with length 1
goroutine 14 [running]:
github.com/terraform-lxd/terraform-provider-lxd/internal/image.splitImageResourceID(...)
	github.com/terraform-lxd/terraform-provider-lxd/internal/image/resource_cached_image.go:476
github.com/terraform-lxd/terraform-provider-lxd/internal/image.CachedImageResource.SyncState({_}, {_, _}, _, {_, _}, {{0x2, {0xc00061c140, 0xb}}, {0x2, ...}, ...})
	github.com/terraform-lxd/terraform-provider-lxd/internal/image/resource_cached_image.go:407 +0xa07
github.com/terraform-lxd/terraform-provider-lxd/internal/image.CachedImageResource.Read({0x0?}, {0xfde028, 0xc00048c510}, {{{{0xfe2cd0, 0xc00048dd40}, {0xd27240, 0xc00048db00}}, {0xfe4a60, 0xc0000bc8c0}}, 0xc000496018, ...}, ...)
	github.com/terraform-lxd/terraform-provider-lxd/internal/image/resource_cached_image.go:304 +0x39e
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ReadResource(0xc00023d380, {0xfde028, 0xc00048c510}, 0xc00048c5a0, 0xc0004e35b0)
	github.com/hashicorp/terraform-plugin-framework@v1.5.0/internal/fwserver/server_readresource.go:101 +0x64e
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ReadResource(0xc00023d380, {0xfde028?, 0xc0000fd860?}, 0xc0000c54c0)
	github.com/hashicorp/terraform-plugin-framework@v1.5.0/internal/proto6server/server_readresource.go:55 +0x3e5
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xc0002375e0, {0xfde028?, 0xc0000fd0e0?}, 0xc0000aa9c0)
	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/tf6server/server.go:787 +0x48b
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0xe2d5e0?, 0xc0002375e0}, {0xfde028, 0xc0000fd0e0}, 0xc0001a3080, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.20.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:467 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000252200, {0xfde028, 0xc0000fd050}, {0xfe39b8, 0xc0003864e0}, 0xc0000ecfc0, 0xc0003531d0, 0x15db168, 0x0)
	google.golang.org/grpc@v1.60.1/server.go:1372 +0xe03
google.golang.org/grpc.(*Server).handleStream(0xc000252200, {0xfe39b8, 0xc0003864e0}, 0xc0000ecfc0)
	google.golang.org/grpc@v1.60.1/server.go:1783 +0xfec
google.golang.org/grpc.(*Server).serveStreams.func2.1()
	google.golang.org/grpc@v1.60.1/server.go:1016 +0x59
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 36
	google.golang.org/grpc@v1.60.1/server.go:1027 +0x115
Error: The terraform-provider-lxd_v2.0.0 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by MusicDin** [comment]
Ahh, I see, its cached image resource_id that is causing issues. Essentially, this attribute is empty prior 2.0, but during update the provider is assuming its populated.

**Comment by matifali** [comment]
@MusicDin After a retry. I am not able to reproduce this issue consistently. I will share the Debug logs the next time I see them. I have enabled debug logs.
